"""Create contact table

Revision ID: 98482c5c4a30
Revises: 5595b1db4f99
Create Date: 2026-09-30 09:47:04.255378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98482c5c4a30'
down_revision = '5595b1db4f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
